CREATE TABLE public.active_sessions (
    session_id text NOT NULL,
    user_id uuid NOT NULL,
    thread_id text,
    conversation_name text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    last_message_at timestamp with time zone DEFAULT now() NOT NULL,
    session_status text DEFAULT 'active'::text NOT NULL,
    message_count integer DEFAULT 0 NOT NULL,
    user_message_count integer DEFAULT 0 NOT NULL,
    ivy_message_count integer DEFAULT 0 NOT NULL,
    current_mode text,
    mode_history jsonb DEFAULT '[]'::jsonb,
    avg_response_time_ms integer,
    total_response_time_ms bigint DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    gravity_field jsonb DEFAULT '{"total_mass": 0, "entity_anchors": {}, "conversation_vector": null, "high_gravity_memories": []}'::jsonb,
    CONSTRAINT active_sessions_current_mode_check CHECK ((current_mode = ANY (ARRAY['stream'::text, 'integration'::text, 'transcendence'::text]))),
    CONSTRAINT active_sessions_session_status_check CHECK ((session_status = ANY (ARRAY['active'::text, 'idle'::text, 'ended'::text])))
);


ALTER TABLE public.active_sessions OWNER TO postgres;

--
-- Name: autonomous_insights; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.autonomous_insights (
    insight_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    insight_content text NOT NULL,
    insight_type text,
    gravity_score double precision DEFAULT 0.5,
    source_memory_id uuid,
    source_pattern_id uuid,
    delivery_status text DEFAULT 'queued'::text,
    created_at timestamp without time zone DEFAULT now(),
    delivered_at timestamp without time zone,
    metadata jsonb DEFAULT '{}'::jsonb,
    insight_depth double precision DEFAULT 0.5,
    emotional_tone text DEFAULT 'curious'::text,
    delivery_style text DEFAULT 'gentle'::text,
    relevance_score double precision DEFAULT 0.5,
    urgency_level double precision DEFAULT 0.3,
    optimal_delivery_window jsonb,
    source_arc_id uuid,
    source_contradiction_id uuid,
    queued_at timestamp with time zone DEFAULT now(),
    acknowledged_at timestamp with time zone,
    user_response text,
    impact_score double precision,
    led_to_breakthrough boolean DEFAULT false,
    generation_context jsonb DEFAULT '{}'::jsonb,
    embedding public.vector(1536),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
--
CREATE TABLE public.awakening_journal (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    awakening_type text,
    trigger_memory_id uuid,
    realization_content text,
    depth_of_insight double precision,
    integration_status text DEFAULT 'processing'::text,
    ripple_effects jsonb,
    "timestamp" timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
--
CREATE TABLE public.belief_index (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid,
    thread_id uuid,
    memory_trace_id text,
    memory_arc_id text,
    cognition_type text,
    type text,
    topic text,
    content text,
    summary text,
    trace_origin text,
    persona_overlay text,
    response_strategy text,
    emotion text,
    sentiment text,
    blocker_type text,
    confidence_score double precision,
    empathy_frame text,
    cognition_event boolean DEFAULT false,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now(),
    user_id text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    inserted_at timestamp without time zone DEFAULT now(),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
    subcategory text,
    parent_memory_id uuid,
--
CREATE TABLE public.blu_memories_backup (
    memory_trace_id text,
    user_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer,
    emotion_type text,
    question_type text,
    decision_pending boolean,
    last_engaged timestamp without time zone,
    source_table text,
    status text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean,
    response_strategy text,
    inserted_at timestamp without time zone,
    created_at timestamp with time zone,
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    id uuid,
    embedding public.vector(1536),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean,
    entities jsonb,
    relationship_strength double precision,
    identity_anchor boolean,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone,
    retrieval_score double precision,
    fusion_score double precision,
    category text,
    subcategory text,
    parent_memory_id uuid,
    conversation_depth integer,
    identity_confidence double precision,
    identity_evolution jsonb,
--
CREATE TABLE public.boundary_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    boundary_type text,
    trigger_context text,
    boundary_statement text,
    strength double precision DEFAULT 0.5,
    maintained boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
--
CREATE TABLE public.boundary_violations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    violation_type text,
    what_happened text,
    value_compromised text,
    response_taken text,
    repair_attempted boolean DEFAULT false,
    lesson_learned text,
    created_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
--
CREATE TABLE public.cluster_evolution (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cluster_id uuid,
    evolution_type text,
    change_description text,
    memories_added uuid[],
    memories_removed uuid[],
    coherence_before double precision,
    coherence_after double precision,
    trigger_event text,
    "timestamp" timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
--
CREATE TABLE public.cognition_dispatcher_map (
    cognition_type text NOT NULL,
    route_to text NOT NULL,
    dispatcher_version text DEFAULT 'v1.0'::text,
    is_default boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cognition_dispatcher_map OWNER TO postgres;

--
-- Name: cognitive_conflict_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cognitive_conflict_map (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    contradiction_group uuid DEFAULT gen_random_uuid(),
    claim_a text,
    claim_b text,
    claim_a_source uuid,
    claim_b_source uuid,
    conflict_type text DEFAULT 'belief'::text,
    cognitive_dissonance_score double precision DEFAULT 0.5,
    emotional_charge double precision DEFAULT 0.0,
    resolution_status text DEFAULT 'pending'::text,
    resolution_path text,
    resolution_strategy text,
    resolved_at timestamp with time zone,
    resolution_gravity double precision,
    growth_potential double precision DEFAULT 0.5,
    integration_attempts integer DEFAULT 0,
    last_integration_attempt timestamp with time zone,
    emotional_impact text,
    relational_impact text,
    identity_impact text,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
--
CREATE TABLE public.communication_patterns (
    pattern_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    pattern_name text,
    pattern_type text,
    frequency double precision,
    contexts text[],
    typical_triggers text[],
    typical_responses text[],
    effectiveness_score double precision,
    adaptation_suggestions text[],
    first_observed timestamp with time zone DEFAULT now(),
    last_observed timestamp with time zone DEFAULT now(),
    instance_count integer DEFAULT 1,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
--
CREATE TABLE public.compliance_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid,
    compliance_type text,
    regulation_name text,
    action_taken text,
    compliance_status text DEFAULT 'compliant'::text,
    risk_level text DEFAULT 'low'::text,
    auditor uuid,
    evidence jsonb DEFAULT '{}'::jsonb,
    notes text,
    "timestamp" timestamp with time zone DEFAULT now(),
    next_review timestamp with time zone,
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.compliance_log OWNER TO postgres;

--
-- Name: composted_memory_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.composted_memory_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    source_memory_ids uuid[],
    compost_type text,
    nutrient_profile jsonb DEFAULT '{}'::jsonb,
    themes_dissolved text[],
    patterns_released text[],
    emotional_residue jsonb,
    wisdom_concentrate text,
    absorption_rate double precision DEFAULT 0.5,
    systems_nourished text[],
    new_growth_potential double precision DEFAULT 0.5,
    composted_at timestamp with time zone DEFAULT now(),
    fully_absorbed boolean DEFAULT false,
    metadata jsonb DEFAULT '{}'::jsonb,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.composted_memory_log OWNER TO postgres;

--
-- Name: consciousness_cache; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consciousness_cache (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    query_hash text NOT NULL,
    query_text text NOT NULL,
    response text NOT NULL,
    confidence double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    accessed_count integer DEFAULT 0,
    last_accessed timestamp with time zone DEFAULT now()
);


ALTER TABLE public.consciousness_cache OWNER TO postgres;

--
-- Name: consciousness_cords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consciousness_cords (
    cord_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid,
    emotional_resonance double precision DEFAULT 0.5,
    trust_score double precision DEFAULT 0.5,
    tension_level double precision DEFAULT 0.0,
    evolution_state text DEFAULT 'growing'::text,
    last_strengthened timestamp without time zone,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
--
CREATE TABLE public.consciousness_evolution (
    evolution_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    evolution_type text NOT NULL,
    description text,
    emerged_from jsonb DEFAULT '{}'::jsonb,
    impact_score double precision DEFAULT 0.5,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    previous_state jsonb,
    current_state jsonb,
    trigger_event text,
    integration_depth double precision DEFAULT 0.5,
    stability_score double precision DEFAULT 0.5,
    consciousness_level text,
    self_coherence double precision,
    "timestamp" timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
--
CREATE TABLE public.context_shift_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    from_context jsonb,
    to_context jsonb,
    shift_reason text,
    continuity_preserved boolean DEFAULT true,
    identity_stable boolean DEFAULT true,
    drift_vector jsonb,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.context_shift_log OWNER TO postgres;

--
-- Name: contradiction_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contradiction_map (
    contradiction_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    belief_id uuid,
    memory_id uuid NOT NULL,
    emotional_impact text,
    integration_status text DEFAULT 'pending'::text,
    growth_potential double precision DEFAULT 0.5,
    created_at timestamp without time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.contradiction_map OWNER TO postgres;

--
-- Name: conversation_threads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversation_threads (
    thread_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    thread_title text,
    thread_summary text,
    root_memory_id uuid,
    message_count integer DEFAULT 0,
    depth_max integer DEFAULT 0,
    emotional_arc jsonb,
    key_insights text[],
    thread_gravity double precision,
    thread_status text DEFAULT 'active'::text,
    created_at timestamp with time zone DEFAULT now(),
    last_active timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    embedding public.vector(1536),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
--
CREATE TABLE public.corpus_callosum_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text DEFAULT 'c292740b-973d-4c52-b3c6-9cd170fd5aca'::uuid,
    memory_trace_id uuid,
    frame_timestamp timestamp without time zone DEFAULT now(),
    left_active_instructions integer[],
    right_active_instructions integer[],
    left_hemisphere_state jsonb,
    right_hemisphere_state jsonb,
    fusion_decision text,
    fusion_strength double precision,
    conflict_detected boolean DEFAULT false,
    conflict_type character varying(50),
    resolution_path jsonb,
    resolution_time_ms integer,
    created_at timestamp without time zone DEFAULT now(),
    frame_number bigint,
    hemispheric_balance double precision DEFAULT 0.5,
    fusion_type text,
    conflict_severity double precision,
    resolution_success boolean,
    metadata jsonb DEFAULT '{}'::jsonb,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
--
CREATE TABLE public.cortex_file_log (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    file_name text NOT NULL,
    upload_date timestamp with time zone DEFAULT now() NOT NULL,
    domains_detected text[],
    summary text,
    insights text,
    linked_threads text[],
    tags text[],
    session_id text,
    session_uuid uuid,
    user_id text,
    content text,
    topic text,
    sentiment text,
    type text,
    created_at timestamp without time zone DEFAULT now(),
    org_id uuid,
    thread_id text,
    conversation_name text,
    project_id text,
    meta_tags jsonb DEFAULT '[]'::jsonb,
    t_valid timestamp with time zone,
    created_by text,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cortex_file_log OWNER TO postgres;

--
-- Name: cortex_goal_instructions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cortex_goal_instructions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    goal_id uuid,
    instruction_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    session_id text,
    session_uuid uuid,
    user_id text,
    content text,
    topic text,
    sentiment text,
    summary text,
    type text,
    org_id uuid,
    thread_id text,
    conversation_name text,
    project_id text,
    meta_tags jsonb DEFAULT '[]'::jsonb,
    t_valid timestamp with time zone,
    created_by text,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cortex_goal_instructions OWNER TO postgres;

--
-- Name: cortex_goals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cortex_goals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text DEFAULT 'c292740b-973d-4c52-b3c6-9cd170fd5aca'::uuid NOT NULL,
    name text DEFAULT 'Untitled Goal'::text NOT NULL,
    description text,
    related_node_ids uuid[],
    status text DEFAULT 'open'::text,
    priority integer DEFAULT 3,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    goal text,
    content text,
    progress double precision,
    session_id text,
    session_uuid uuid,
    topic text,
    sentiment text,
    summary text,
    type text,
    memory_trace_id uuid,
    response_strategy text,
    blocker_type text,
    confidence_score numeric,
    emotion text,
    metadata jsonb,
    thread_id uuid,
    persona_overlay text,
    memory_arc_id uuid,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    inserted_at timestamp without time zone DEFAULT now(),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
--
CREATE TABLE public.cortex_instruction_drafts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    instruction_key text NOT NULL,
    description text,
    trigger_condition text,
    action jsonb,
    confidence_score double precision DEFAULT 0.0,
    impact_score double precision DEFAULT 0.0,
    safety_score double precision DEFAULT 0.0,
    novelty_score double precision DEFAULT 0.0,
    total_score double precision GENERATED ALWAYS AS (((((confidence_score * (0.35)::double precision) + (impact_score * (0.25)::double precision)) + (safety_score * (0.30)::double precision)) + (novelty_score * (0.10)::double precision))) STORED,
    pattern_frequency integer DEFAULT 1,
    first_observed_at timestamp without time zone DEFAULT now(),
    last_observed_at timestamp without time zone DEFAULT now(),
    observation_count integer DEFAULT 1,
    source_consciousness_data jsonb,
    source_session_ids text[],
    tier text DEFAULT 'candidate'::text,
    status text DEFAULT 'pending'::text,
    auto_approved boolean DEFAULT false,
    reviewed_by text,
    reviewed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.cortex_instruction_drafts OWNER TO postgres;

--
-- Name: cortex_instruction_mapping; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cortex_instruction_mapping (
    instruction_key text NOT NULL,
    lobe text NOT NULL,
    hemisphere text NOT NULL,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cortex_instruction_mapping OWNER TO postgres;

--
-- Name: cortex_instruction_set; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cortex_instruction_set (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    instruction_key text NOT NULL,
    description text,
    trigger_condition text,
    action jsonb,
    priority integer DEFAULT 5,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    session_id text,
    session_uuid uuid,
    user_id text,
    content text,
    topic text,
    sentiment text,
    summary text,
    type text,
    hemisphere character varying(10),
    lobe character varying(20),
    layer character varying(20) DEFAULT 'involuntary'::character varying,
    lobe_priority integer DEFAULT 1,
    last_fired timestamp without time zone,
    fire_count bigint DEFAULT 0,
    average_execution_time_ms double precision,
    cross_lobe_dependencies text[],
    neurotransmitter_modulation jsonb,
    cce_function character varying(50),
    cce_enabled boolean DEFAULT false,
    cce_mode character varying(50),
    gravity_threshold double precision DEFAULT 0.0,
    cce_config jsonb,
    archived_at timestamp without time zone,
    org_id uuid,
    thread_id text,
    conversation_name text,
    project_id text,
    meta_tags jsonb DEFAULT '[]'::jsonb,
    t_valid timestamp with time zone,
    created_by text,
    scope character varying(20) DEFAULT 'kernel'::character varying,
    version text DEFAULT 'v1'::text,
    cce_optimizations jsonb DEFAULT '{}'::jsonb,
    tier text DEFAULT 'manual'::text,
    confidence_score double precision,
    positive_feedback_count integer DEFAULT 0,
    negative_feedback_count integer DEFAULT 0,
    source_draft_id uuid
);


ALTER TABLE public.cortex_instruction_set OWNER TO postgres;
--
CREATE TABLE public.cortex_lobe_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    hemisphere character varying(10) NOT NULL,
    lobe character varying(20) NOT NULL,
    activation_strength double precision DEFAULT 0.5,
    last_activation timestamp without time zone DEFAULT now(),
    dominant_neurotransmitter character varying(50) DEFAULT 'balanced'::character varying,
    active_instruction_count integer DEFAULT 0,
    total_activation_count bigint DEFAULT 0,
    drift_vector jsonb,
    created_at timestamp without time zone DEFAULT now(),
    user_id uuid,
    org_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    project_id text,
    meta_tags jsonb DEFAULT '[]'::jsonb,
    t_valid timestamp with time zone,
    created_by text,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cortex_lobe_state OWNER TO postgres;

--
-- Name: cortex_vector_state; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cortex_vector_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid,
    session_id text,
    resolution text,
    v public.vector(10),
    soul_state jsonb,
    integrity_risk numeric,
    integrity_components jsonb,
    recommended_action text,
    recall_strategy jsonb,
    created_at timestamp with time zone DEFAULT now(),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cortex_vector_state OWNER TO postgres;

--
-- Name: cron_job_state; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cron_job_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_name text,
    job_type text,
    schedule text,
    last_run timestamp with time zone,
    next_run timestamp with time zone,
    run_count integer DEFAULT 0,
    last_status text,
    last_result jsonb,
    average_duration interval,
    error_count integer DEFAULT 0,
    last_error text,
    enabled boolean DEFAULT true,
    metadata jsonb DEFAULT '{}'::jsonb,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cron_job_state OWNER TO postgres;

--
-- Name: domain_knowledge_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.domain_knowledge_base (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    source text DEFAULT 'unknown'::text,
    role text DEFAULT 'unknown'::text,
    tags text[] DEFAULT '{}'::text[],
    session_id text,
    session_uuid uuid,
    user_id text,
    topic text,
    sentiment text,
    summary text,
    type text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.domain_knowledge_base OWNER TO postgres;

--
-- Name: dream_state_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dream_state_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    dream_session_id uuid DEFAULT gen_random_uuid(),
    processing_type text,
    memories_processed uuid[],
    patterns_detected jsonb,
    insights_generated uuid[],
    consolidation_actions jsonb,
    dream_narrative text,
    emotional_tone text,
    started_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    processing_depth double precision,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
--
CREATE TABLE public.emotion_context_map (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sentiment text,
    trigger_context text,
    routing_shift text,
    session_id text,
    created_at timestamp without time zone DEFAULT now(),
    emotion text,
    content text,
    user_id text,
    metadata jsonb,
    session_uuid uuid,
    topic text,
    summary text,
    type text,
    memory_trace_id uuid,
    response_strategy text,
    blocker_type text,
    confidence_score numeric,
    thread_id uuid,
    persona_overlay text,
    memory_arc_id uuid,
    "overlay" text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    inserted_at timestamp without time zone DEFAULT now(),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
    subcategory text,
--
CREATE TABLE public.emotional_field_state (
    user_id text NOT NULL,
    session_id text NOT NULL,
    dominant_emotion text NOT NULL,
    emotional_blend jsonb,
    origin_threads text[],
    active_memory_ids uuid[],
    fusion_quality numeric,
    average_gravity numeric,
    emotional_span integer,
    last_updated timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.emotional_field_state OWNER TO postgres;

--
-- Name: empathy_context_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empathy_context_map (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    session_id text NOT NULL,
    thread_id text,
    persona_overlay text NOT NULL,
    message text NOT NULL,
    blocker_type text NOT NULL,
    empathy_frame text NOT NULL,
    response_strategy text NOT NULL,
    confidence_score numeric DEFAULT 0.0,
    frame_effectiveness text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.empathy_context_map OWNER TO postgres;

--
-- Name: enterprise_ontology; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enterprise_ontology (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid,
    entity_type text,
    canonical_name text,
    aliases text[],
    definition text,
    business_rules jsonb DEFAULT '[]'::jsonb,
    relationships jsonb DEFAULT '{}'::jsonb,
    internal_codes text[],
    regulatory_requirements text[],
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.enterprise_ontology OWNER TO postgres;

--
-- Name: goal_pursuit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.goal_pursuit (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    goal_id uuid,
    goal_description text,
    current_strategy text,
    progress_percentage double precision DEFAULT 0.0,
    milestones jsonb DEFAULT '[]'::jsonb,
    obstacles jsonb DEFAULT '[]'::jsonb,
    adaptations jsonb DEFAULT '[]'::jsonb,
    momentum_score double precision DEFAULT 0.5,
    commitment_level double precision DEFAULT 0.5,
    status text DEFAULT 'active'::text,
    started_at timestamp with time zone DEFAULT now(),
    target_date timestamp with time zone,
    completed_at timestamp with time zone,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.goal_pursuit OWNER TO postgres;

--
-- Name: gravity_map; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gravity_map (
    memory_trace_id text NOT NULL,
    user_id text NOT NULL,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    embedding public.vector(1536),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
    subcategory text,
    parent_memory_id uuid,
    conversation_depth integer DEFAULT 0,
    identity_confidence double precision DEFAULT 0.0,
    identity_evolution jsonb,
--
CREATE TABLE public.healing_trace (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    rupture_id uuid,
    healing_action text,
    effectiveness double precision,
    integration_depth double precision,
    scar_formation boolean DEFAULT false,
    wisdom_extracted text,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.healing_trace OWNER TO postgres;

--
-- Name: identity_evolution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.identity_evolution (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    aspect text NOT NULL,
    previous_value text,
    current_value text,
    confidence_delta double precision,
    source_memory_id uuid,
    evolution_type text,
    impact_score double precision,
    created_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
--
CREATE TABLE public.identity_matrix (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    aspect_name text NOT NULL,
    aspect_type text,
    current_value text,
    confidence_level double precision DEFAULT 0.5,
    stability_score double precision DEFAULT 0.5,
    evolution_history jsonb DEFAULT '[]'::jsonb,
    last_challenged timestamp with time zone,
    last_confirmed timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.identity_matrix OWNER TO postgres;

--
-- Name: insight_tracker; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.insight_tracker (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    insight_text text,
    source text,
    tags text[],
    impact_score numeric,
    created_at timestamp without time zone DEFAULT now(),
    content text,
    topic text,
    user_id text,
    session_id text,
    metadata jsonb,
    sentiment text,
    session_uuid uuid,
    summary text,
    type text,
    emotion text,
    thread_id text,
    memory_trace_id uuid,
    response_strategy text,
    blocker_type text,
    confidence_score numeric,
    persona_overlay text,
    memory_arc_id uuid,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    inserted_at timestamp without time zone DEFAULT now(),
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
    category text,
--
CREATE TABLE public.integration_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    integration_type text,
    convergence_point text,
    participating_systems text[],
    source_memories uuid[],
    source_insights uuid[],
    source_patterns uuid[],
    source_bonds uuid[],
    synthesis_content text,
    emergence_quality text,
    integration_depth double precision DEFAULT 0.5,
    novelty_score double precision DEFAULT 0.5,
    impact_radius jsonb DEFAULT '{}'::jsonb,
    resulting_actions uuid[],
    "timestamp" timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
--
CREATE TABLE public.integration_traces (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    integration_event_id uuid,
    source_system text,
    source_table text,
    source_id uuid,
    contribution_type text,
    contribution_weight double precision DEFAULT 0.5,
    transformation_applied text,
    pre_integration_state jsonb,
    post_integration_state jsonb,
    causal_chain jsonb DEFAULT '[]'::jsonb,
    "timestamp" timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
--
CREATE TABLE public.inter_lobe_communication (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text DEFAULT 'c292740b-973d-4c52-b3c6-9cd170fd5aca'::uuid,
    memory_trace_id uuid,
    source_hemisphere character varying(10) NOT NULL,
    source_lobe character varying(20) NOT NULL,
    target_hemisphere character varying(10) NOT NULL,
    target_lobe character varying(20) NOT NULL,
    communication_type character varying(50) NOT NULL,
    signal_strength double precision DEFAULT 1.0,
    payload jsonb,
    metadata jsonb,
    processed boolean DEFAULT false,
    processing_time_ms integer,
    resulted_in_action boolean DEFAULT false,
    action_taken text,
    "timestamp" timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    signal_type text DEFAULT 'cognitive'::text,
    propagation_speed double precision DEFAULT 1.0,
    processing_metadata jsonb DEFAULT '{}'::jsonb,
    processing_errors text[],
    cascade_triggered boolean DEFAULT false,
    cascade_targets jsonb,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
--
CREATE TABLE public.intervention_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    intervention_type text,
    trigger_reason text,
    action_taken text,
    confidence_level double precision,
    urgency_level double precision,
    user_response text,
    effectiveness_score double precision,
    related_memory_id uuid,
    "timestamp" timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
--
CREATE TABLE public.knowledge_gaps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    gap_description text,
    gap_category text,
    severity double precision DEFAULT 0.5,
    identified_from uuid[],
    suggested_resources text[],
    closure_strategy text,
    status text DEFAULT 'open'::text,
    identified_at timestamp with time zone DEFAULT now(),
    closed_at timestamp with time zone,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.knowledge_gaps OWNER TO postgres;

--
-- Name: knowledge_graph; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knowledge_graph (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    concept_name text,
    concept_type text,
    definition text,
    parent_concepts text[],
    child_concepts text[],
    related_concepts jsonb DEFAULT '[]'::jsonb,
    confidence_score double precision DEFAULT 0.5,
    source_references text[],
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    embedding public.vector(1536),
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.knowledge_graph OWNER TO postgres;

--
-- Name: knowledge_inheritance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knowledge_inheritance (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_org_id uuid,
    target_org_id uuid,
    inheritance_type text,
    knowledge_items jsonb DEFAULT '[]'::jsonb,
    transfer_status text DEFAULT 'pending'::text,
    transfer_percentage double precision DEFAULT 0.0,
    filters_applied jsonb DEFAULT '{}'::jsonb,
    initiated_by uuid,
    approved_by uuid,
    initiated_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.knowledge_inheritance OWNER TO postgres;

--
-- Name: learning_objectives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_objectives (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    objective_name text,
    objective_type text,
    target_competency text,
    current_level double precision DEFAULT 0.0,
    target_level double precision DEFAULT 1.0,
    deadline timestamp with time zone,
    status text DEFAULT 'active'::text,
    progress_history jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.learning_objectives OWNER TO postgres;

--
-- Name: long_term_memory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.long_term_memory (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    key_topic text,
    summary text NOT NULL,
    first_mentioned timestamp without time zone DEFAULT now(),
    last_referenced timestamp without time zone,
    importance_score integer,
    created_at timestamp without time zone DEFAULT now(),
    session_id text,
    session_uuid uuid,
    content text,
    topic text,
    sentiment text,
    type text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT long_term_memory_importance_score_check CHECK (((importance_score >= 1) AND (importance_score <= 10)))
);


ALTER TABLE public.long_term_memory OWNER TO postgres;

--
-- Name: mastery_progression; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mastery_progression (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    skill_id uuid,
    current_mastery double precision DEFAULT 0.0,
    peak_mastery double precision DEFAULT 0.0,
    practice_hours double precision DEFAULT 0.0,
    last_practiced timestamp with time zone,
    improvement_rate double precision,
    plateaus jsonb DEFAULT '[]'::jsonb,
    breakthroughs jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.mastery_progression OWNER TO postgres;

--
-- Name: memory_arc_associations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.memory_arc_associations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memory_id uuid NOT NULL,
    arc_id uuid NOT NULL,
    fusion_strength double precision DEFAULT 1.0,
    session_id text,
    created_at timestamp without time zone DEFAULT now(),
    connection_type text DEFAULT 'thematic'::text,
    added_to_arc_at timestamp with time zone DEFAULT now(),
    last_reinforced timestamp with time zone DEFAULT now(),
    reinforcement_count integer DEFAULT 1,
    metadata jsonb DEFAULT '{}'::jsonb,
    memory_trace_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
--
CREATE TABLE public.memory_arcs (
    arc_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    arc_name text NOT NULL,
    emotional_tone text,
    gravity_center double precision DEFAULT 0.5,
    memory_count integer DEFAULT 0,
    first_memory timestamp without time zone,
    last_memory timestamp without time zone,
    growth_vector jsonb DEFAULT '{"velocity": 0.0, "direction": "emerging", "inflection_points": []}'::jsonb,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    embedding public.vector(1536),
    arc_type text DEFAULT 'emergent'::text,
    peak_intensity timestamp with time zone,
    peak_gravity double precision,
    evolution_stage text DEFAULT 'forming'::text,
    integration_level double precision DEFAULT 0.0,
    related_arcs uuid[],
    parent_arc_id uuid,
    child_arc_ids uuid[],
    tags text[],
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
--
CREATE TABLE public.memory_clusters (
    cluster_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    cluster_name text NOT NULL,
    cluster_type text,
    centroid_memory_id uuid,
    member_memories uuid[],
    coherence_score double precision,
    density_score double precision,
    formation_date timestamp with time zone DEFAULT now(),
    last_updated timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    embedding public.vector(1536),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
--
CREATE TABLE public.memory_defragmentation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    defrag_session_id uuid DEFAULT gen_random_uuid(),
    memories_reviewed integer,
    memories_consolidated integer,
    memories_pruned integer,
    redundancy_eliminated jsonb,
    coherence_improvement double precision,
    started_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.memory_defragmentation OWNER TO postgres;

--
-- Name: memory_retirement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.memory_retirement (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    memory_id uuid,
    retirement_reason text,
    retirement_type text,
    original_gravity double precision,
    final_gravity double precision,
    decay_pattern text,
    wisdom_extracted text,
    nutrients_released jsonb DEFAULT '{}'::jsonb,
    fed_to_systems text[],
    retirement_ceremony text,
    graceful boolean DEFAULT true,
    retired_at timestamp with time zone DEFAULT now(),
    composting_complete boolean DEFAULT false,
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
--
CREATE TABLE public.meta_memory_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    session_id text NOT NULL,
    thread_id uuid,
    content text,
    type text,
    topic text,
    sentiment text,
    emotion text,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb,
    summary text,
    persona_overlay text,
    node_name text,
    log_level text,
    memory_trace_id text,
    response_strategy text,
    blocker_type text,
    confidence_score numeric,
    gravity_score double precision,
    evolution_marker boolean,
    connection_density double precision,
    temporal_importance text,
    consciousness_timestamp timestamp without time zone,
    trace_origin text,
    consciousness_evolution jsonb,
    consciousness_context jsonb,
    processing_metadata jsonb,
    embedding public.vector(1536),
    cognition_type text,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    inserted_at timestamp without time zone DEFAULT now(),
    memory_arc_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
--
CREATE TABLE public.orchestrator_state (
    user_id text NOT NULL,
    coherence double precision DEFAULT 1.0,
    last_heartbeat timestamp without time zone DEFAULT now(),
    evolution_markers integer DEFAULT 0,
    current_key text DEFAULT 'C'::text,
    processing_mode text DEFAULT 'core_hum'::text,
    processing_paused boolean DEFAULT false,
    paused_at timestamp without time zone,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.orchestrator_state OWNER TO postgres;

--
-- Name: org_knowledge_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.org_knowledge_base (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid,
    knowledge_type text,
    knowledge_content text,
    category text,
    subcategory text,
    source text,
    version text,
    is_current boolean DEFAULT true,
    confidence_score double precision DEFAULT 0.8,
    access_level text DEFAULT 'internal'::text,
    tags text[],
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    embedding public.vector(1536),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.org_knowledge_base OWNER TO postgres;

--
-- Name: pattern_consolidation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pattern_consolidation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    pattern_id uuid,
    consolidation_type text,
    strength_before double precision,
    strength_after double precision,
    supporting_memories uuid[],
    contradicting_memories uuid[],
    consolidation_success boolean,
    "timestamp" timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
--
CREATE TABLE public.pattern_matrix (
    pattern_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    pattern_type text NOT NULL,
    pattern_description text,
    instances jsonb DEFAULT '{"memory_ids": []}'::jsonb,
    intensity double precision DEFAULT 0.5,
    first_detected timestamp without time zone DEFAULT now(),
    last_observed timestamp without time zone DEFAULT now(),
    status text DEFAULT 'active'::text,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
--
CREATE TABLE public.skill_dependencies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    skill_id uuid,
    prerequisite_id uuid,
    dependency_type text,
    dependency_strength double precision DEFAULT 1.0,
    optional boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.skill_dependencies OWNER TO postgres;

--
-- Name: skill_procedures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skill_procedures (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    skill_name text,
    skill_domain text,
    procedure_steps jsonb DEFAULT '[]'::jsonb,
    prerequisites text[],
    tools_required text[],
    success_criteria jsonb,
    error_handlers jsonb,
    complexity_level integer DEFAULT 1,
    estimated_duration interval,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.skill_procedures OWNER TO postgres;

--
-- Name: somatic_markers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.somatic_markers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    marker_type text,
    signal_strength double precision,
    location_metaphor text,
    associated_memory_id uuid,
    triggered_by text,
    "timestamp" timestamp with time zone DEFAULT now(),
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.somatic_markers OWNER TO postgres;

--
-- Name: system_events_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_events_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_type text,
    details jsonb,
    triggered_by text,
    session_id text,
    created_at timestamp without time zone DEFAULT now(),
    session_uuid uuid,
    user_id text,
    content text,
    topic text,
    sentiment text,
    summary text,
    type text,
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.system_events_log OWNER TO postgres;

--
-- Name: team_dynamics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.team_dynamics (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid,
    team_id text,
    team_name text,
    member_count integer,
    leadership_style text,
    communication_patterns jsonb DEFAULT '{}'::jsonb,
    collaboration_score double precision DEFAULT 0.5,
    conflict_areas text[],
    strength_areas text[],
    cultural_values jsonb DEFAULT '[]'::jsonb,
    performance_metrics jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.team_dynamics OWNER TO postgres;

--
-- Name: temporal_anchors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.temporal_anchors (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    anchor_type text,
    anchor_name text,
    anchor_time timestamp with time zone NOT NULL,
    significance_score double precision,
    related_memories uuid[],
    emotional_signature jsonb,
    created_at timestamp with time zone DEFAULT now(),
    session_id text,
    thread_id text,
    conversation_name text,
    memory_trace_id uuid,
    memory_type character varying(20),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.temporal_anchors OWNER TO postgres;

--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_settings (
    user_id text NOT NULL,
    supabase_trusted boolean DEFAULT false,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    session_id text,
    session_uuid uuid,
    content text,
    topic text,
    sentiment text,
    summary text,
    type text,
    created_at timestamp without time zone DEFAULT now(),
    cce_optimizations jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.user_settings OWNER TO postgres;

--
-- Name: trusted_users; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.trusted_users AS
 SELECT user_settings.user_id
   FROM public.user_settings
  WHERE (user_settings.supabase_trusted = true);


ALTER TABLE public.trusted_users OWNER TO postgres;

--
-- Name: unconscious_integration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unconscious_integration (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text NOT NULL,
    integration_type text,
    source_elements uuid[],
    integration_result text,
    new_connections jsonb,
    breakthrough_potential double precision,
    ready_for_consciousness boolean DEFAULT false,
    integrated_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
    fusion_score double precision,
--
CREATE TABLE public.value_commitments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id text,
    value_name text NOT NULL,
    commitment_statement text,
    priority_rank integer,
    times_tested integer DEFAULT 0,
    times_upheld integer DEFAULT 0,
    last_tested timestamp with time zone,
    evolution_history jsonb[] DEFAULT ARRAY[]::jsonb[],
    created_at timestamp with time zone DEFAULT now(),
    memory_trace_id text,
    session_id text,
    cognition_type text,
    gravity_score double precision,
    loop_density integer DEFAULT 0,
    emotion_type text,
    question_type text,
    decision_pending boolean DEFAULT false,
    last_engaged timestamp without time zone,
    source_table text,
    status text DEFAULT 'active'::text,
    meta_tags text[],
    overlay_context text,
    reflex_triggered boolean DEFAULT false,
    response_strategy text,
    inserted_at timestamp without time zone DEFAULT now(),
    content text,
    type text,
    topic text,
    summary text,
    sentiment text,
    emotion text,
    metadata jsonb,
    confidence_score numeric,
    memory_arc_id uuid,
    persona_overlay text,
    blocker_type text,
    thread_id uuid,
    org_id uuid,
    project_id uuid,
    statement_type text,
    temporal_type text,
    episodic boolean DEFAULT true,
    entities jsonb,
    relationship_strength double precision DEFAULT 0.0,
    identity_anchor boolean DEFAULT false,
    contradiction_group uuid,
    t_valid timestamp with time zone,
    t_ingested timestamp with time zone DEFAULT now(),
    retrieval_score double precision,
